class Config {
  static Map<String, dynamic> getDefault() {
    return {
      "main_tags": [
        {
          "tag1": "Driving",
          "tag2": [
            "Stuck in traffic",
            "Was Tailgated",
            "Got Honked",
            "Experienced aggressive cutoff",
            "Was high beamed",
            "Experienced near accident",
            "Stuck at a railroad crossing",
            "Saw a police car",
            "Stopped by police",
            "Poor visibility",
            "Wet/icy road conditions",
            "Hazardous road surface",
            "Unsafe neighbourhood",
            "Difficulty in navigating",
            "Interference/distraction from passengers",
            "Too many incoming texts/calls while driving",
            "Indecision at a traffic intersection"
          ]
        },
        {
          "tag1": "Job",
          "tag2": [
            "Late arrival",
            "Unanticipated task",
            "Approaching deadline",
            "Unpleasant conversation",
            "Negative feedback",
            "Missed deadline",
            "Bored / Not enough to do",
            "Slowing business",
            "Technology barriers",
            "Uncomfortable with change",
            "Workplace politics",
            "Exceeding personal capacity",
            "Forced/uninteresting  work",
            "Faced Discrimination",
            "Unfair compensation",
            "Faced harassment",
            "Subjected to bullying",
            "Too much workload/responsibilities",
            "Unsafe Work conditions/ environment",
            "Long/inconvenient hours",
            "Give presentations in front of colleagues",
            "Unclear expectations",
            "No say in decision making",
            "Too much / forced travelling",
            "Interpersonal conflict",
            "Job instability",
            "Unpleasant communication (email, text, voicemail, slack, etc.)",
            "Notification (e.g. performance appraisal, customers, HR)",
            "Lost business opportunity",
            "Communication barriers",
            "Experienced passive-aggressive behaviour",
            "Was misrepresented"
          ]
        },
        {
          "tag1": "Finance",
          "tag2": [
            "Behind in debt payments",
            "Can't pay bills due",
            "Missed payment",
            "Unexpected expense",
            "Can’t afford .... (something )",
            "Unexpected losses (trading e.x.)",
            "Experienced financial fraud",
            "Dealing with lost/stolen/cancelled cards"
          ]
        },
        {
          "tag1": "Friends/Family",
          "tag2": [
            "Conflict with a partner",
            "Health issues with family/friends",
            "Children fighting",
            "Children’s academics",
            "Children’s behaviour",
            "Conflict with Friends",
            "Dealing with separation in the family",
            "Drug or alcohol use or addiction in the family",
            "At the risk of or going through Divorce",
            "Taking care of elderly or sick family member",
            "Interaction with Inlaws"
          ]
        },
        {
          "tag1": "Health",
          "tag2": [
            "Mental Health",
            "Physical inability",
            "Chronic illness",
            "Pain",
            "My eating habits",
            "Lack of food",
            "Craving (e.g. addiction)"
          ]
        },
        {
          "tag1": "Personal",
          "tag2": [
            "Unmet/upcoming obligation/responsibility",
            "Holiday season",
            "Exam preparation",
            "Bad weather",
            "Concerned with my safety"
          ]
        },
        {
          "tag1": "Social Media",
          "tag2": [
            "Feeling judged",
            "Feeling bad about social media use",
            "Faced cyberbullying",
            "Anxiety"
          ]
        },
        {
          "tag1": "Safety",
          "tag2": [
            "Natural disaster",
            "Theft",
            "Rape",
            "Assault",
            "Confrontation",
            "Robbery"
          ]
        }
      ],
      "core_id": "core",
      "core_enable": true,
      "core_config_id": "decisions",
      "core_config_title": "Decisions",
      "core_config_description": "Configuration file for Decisions app",
      "core_config_version": "4.0.1",
      "core_datakit_active": true,
      "core_upload_enable": true,
      "core_upload_time": 30000,
      "core_login_userId": "9QTE4OVGZfVoEP7Hy3XnuWofKRb2",
      "core_upload_wifiOnly": true,
      "phonesensor_id": "phonesensor",
      "phonesensor_title": "Phone Sensor",
      "phonesensor_description":
          "Collects phone sensor data (accelerometer, gyroscope, GPS, Activity Type, Battery level, etc)",
      "phonesensor_enable": true,
      "phonesensor_accelerometer_enable": false,
      "phonesensor_accelerometer_sampleRate": 16,
      "phonesensor_accelerometer_sampleRateUnit": "SECONDS",
      "phonesensor_accelerometer_writeType": "FIXED",
      "phonesensor_accelerometer_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_accelerometer_writeOnChangeValue": 0.1,
      "phonesensor_accelerometerLinear_enable": false,
      "phonesensor_accelerometerLinear_sampleRate": 16,
      "phonesensor_accelerometerLinear_sampleRateUnit": "SECONDS",
      "phonesensor_accelerometerLinear_writeType": "FIXED",
      "phonesensor_accelerometerLinear_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_accelerometerLinear_writeOnChangeValue": 0.1,
      "phonesensor_gyroscope_enable": false,
      "phonesensor_gyroscope_sampleRate": 16,
      "phonesensor_gyroscope_sampleRateUnit": "SECONDS",
      "phonesensor_gyroscope_writeType": "FIXED",
      "phonesensor_gyroscope_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_gyroscope_writeOnChangeValue": 0.1,
      "phonesensor_magnetometer_enable": false,
      "phonesensor_magnetometer_sampleRate": 16,
      "phonesensor_magnetometer_sampleRateUnit": "SECONDS",
      "phonesensor_magnetometer_writeType": "FIXED",
      "phonesensor_magnetometer_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_magnetometer_writeOnChangeValue": 0.1,
      "phonesensor_gravity_enable": false,
      "phonesensor_gravity_sampleRate": 16,
      "phonesensor_gravity_sampleRateUnit": "SECONDS",
      "phonesensor_gravity_writeType": "FIXED",
      "phonesensor_gravity_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_gravity_writeOnChangeValue": 0.1,
      "phonesensor_ambientLight_enable": false,
      "phonesensor_ambientLight_sampleRate": 16,
      "phonesensor_ambientLight_sampleRateUnit": "SECONDS",
      "phonesensor_ambientLight_writeType": "FIXED",
      "phonesensor_ambientLight_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_ambientLight_writeOnChangeValue": 0.1,
      "phonesensor_airPressure_enable": false,
      "phonesensor_airPressure_sampleRate": 16,
      "phonesensor_airPressure_sampleRateUnit": "SECONDS",
      "phonesensor_airPressure_writeType": "FIXED",
      "phonesensor_airPressure_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_airPressure_writeOnChangeValue": 0.1,
      "phonesensor_ambientTemperature_enable": false,
      "phonesensor_ambientTemperature_sampleRate": 16,
      "phonesensor_ambientTemperature_sampleRateUnit": "SECONDS",
      "phonesensor_ambientTemperature_writeType": "FIXED",
      "phonesensor_ambientTemperature_writeOnChangeType": "SAMPLE_DIFFERENCE",
      "phonesensor_ambientTemperature_writeOnChangeValue": 0.1,
      "phonesensor_proximity_enable": false,
      "phonesensor_proximity_sampleRate": 6,
      "phonesensor_proximity_sampleRateUnit": "SECONDS",
      "phonesensor_proximity_writeType": "ON_CHANGE",
      "phonesensor_proximity_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_proximity_writeOnChangeValue": 0.1,
      "phonesensor_relativeHumidity_enable": false,
      "phonesensor_relativeHumidity_sampleRate": 6,
      "phonesensor_relativeHumidity_sampleRateUnit": "SECONDS",
      "phonesensor_relativeHumidity_writeType": "ON_CHANGE",
      "phonesensor_relativeHumidity_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_relativeHumidity_writeOnChangeValue": 0.1,
      "phonesensor_significantMotion_enable": false,
      "phonesensor_significantMotion_writeType": "AS_RECEIVED",
      "phonesensor_chargingStatus_enable": false,
      "phonesensor_chargingStatus_writeType": "ON_CHANGE",
      "phonesensor_chargingStatus_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_connectivityStatus_enable": false,
      "phonesensor_connectivityStatus_writeType": "ON_CHANGE",
      "phonesensor_connectivityStatus_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_bluetoothStatus_enable": true,
      "phonesensor_bluetoothStatus_writeType": "ON_CHANGE",
      "phonesensor_bluetoothStatus_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_gpsStatus_enable": true,
      "phonesensor_gpsStatus_writeType": "ON_CHANGE",
      "phonesensor_gpsStatus_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_wifiStatus_enable": false,
      "phonesensor_wifiStatus_writeType": "ON_CHANGE",
      "phonesensor_wifiStatus_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_battery_enable": true,
      "phonesensor_battery_writeType": "ON_CHANGE",
      "phonesensor_battery_sampleRate": 1,
      "phonesensor_battery_sampleRateUnit": "MINUTES",
      "phonesensor_battery_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_battery_writeOnChangeValue": 0.1,
      "phonesensor_activityType_enable": true,
      "phonesensor_activityType_sampleRate": 1,
      "phonesensor_activityType_sampleRateUnit": "MINUTES",
      "phonesensor_activityType_writeType": "AS_RECEIVED",
      "phonesensor_activityType_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_activityType_writeOnChangeValue": 0.1,
      "phonesensor_gps_enable": true,
      "phonesensor_gps_sampleRate": 12,
      "phonesensor_gps_sampleRateUnit": "MINUTES",
      "phonesensor_gps_writeType": "AS_RECEIVED",
      "phonesensor_gps_writeOnChangeType": "NOT_EQUAL",
      "phonesensor_gps_writeOnChangeValue": 0.1,
      "phonesensor_stepCount_enable": false,
      "phonesensor_stepCount_sampleRate": 1,
      "phonesensor_stepCount_sampleRateUnit": "MINUTES",
      "phonesensor_stepCount_writeType": "FIXED"
    };
  }
}
