package org.md2k.mcerebrumapi.datakitapi.datasource.unit;

/*
 * Copyright (c) 2016, The University of Memphis, MD2K Center
 * - Syed Monowar Hossain <monowar.hossain@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

public enum MCUnit {
    ACRE,
    ACRE_FOOT,
    AMPERE,
    ARC_MINUTE,
    ARC_SECOND,
    ASTRONOMICAL_UNIT,
    BIT,
    BUSHEL,
    BYTE,
    CALORIE,
    CARAT,
    CELSIUS,
    CENTILITER,
    CENTIMETER,
    CENTURY,
    CUBIC_CENTIMETER,
    CUBIC_FOOT,
    CUBIC_INCH,
    CUBIC_KILOMETER,
    CUBIC_METER,
    CUBIC_MILE,
    CUBIC_YARD,
    CUP,
    CUP_METRIC,
    DAY,
    DECILITER,
    DECIMETER,
    DEGREE,
    FAHRENHEIT,
    FATHOM,
    FLUID_OUNCE,
    FOODCALORIE,
    FOOT,
    FURLONG,
    GALLON,
    GALLON_IMPERIAL,
    GENERIC_TEMPERATURE,
    GIGABIT,
    GIGABYTE,
    GIGAHERTZ,
    GIGAWATT,
    GRAM,
    G_FORCE,
    HECTARE,
    HECTOLITER,
    HECTOPASCAL,
    HERTZ,
    HORSEPOWER,
    HOUR,
    INCH,
    INCH_HG,
    JOULE,
    KARAT,
    KELVIN,
    KILOBIT,
    KILOBYTE,
    KILOCALORIE,
    KILOGRAM,
    KILOHERTZ,
    KILOJOULE,
    KILOMETER,
    KILOMETER_PER_HOUR,
    KILOWATT,
    KILOWATT_HOUR,
    KNOT,
    LIGHT_YEAR,
    LITER,
    LITER_PER_100KILOMETERS,
    LITER_PER_KILOMETER,
    LUX,
    MEGABIT,
    MEGABYTE,
    MEGAHERTZ,
    MEGALITER,
    MEGAWATT,
    METER,
    METER_PER_SECOND,
    METER_PER_SECOND_SQUARED,
    METRIC_TON,
    MICROGRAM,
    MICROMETER,
    MICROSECOND,
    MILE,
    MILE_PER_GALLON,
    MILE_PER_GALLON_IMPERIAL,
    MILE_PER_HOUR,
    MILE_SCANDINAVIAN,
    MILLIAMPERE,
    MILLIBAR,
    MILLIGRAM,
    MILLIGRAM_PER_DECILITER,
    MILLILITER,
    MILLIMETER,
    MILLIMETER_OF_MERCURY,
    MILLIMOLE_PER_LITER,
    MILLISECOND,
    MILLIWATT,
    MINUTE,
    MONTH,
    NO_UNIT,
    NANOMETER,
    NANOSECOND,
    NAUTICAL_MILE,
    OHM,
    OUNCE,
    OUNCE_TROY,
    PARSEC,
    PART_PER_MILLION,
    PERCENTAGE,
    PICOMETER,
    PINT,
    PINT_METRIC,
    POUND,
    POUND_PER_SQUARE_INCH,
    QUART,
    RADIAN,
    RADIAN_PER_SECOND,
    REVOLUTION_ANGLE,
    SECOND,
    SQUARE_CENTIMETER,
    SQUARE_FOOT,
    SQUARE_INCH,
    SQUARE_KILOMETER,
    SQUARE_METER,
    SQUARE_MILE,
    SQUARE_YARD,
    STONE,
    TABLESPOON,
    TEASPOON,
    TERABIT,
    TERABYTE,
    TON,
    VOLT,
    WATT,
    WEEK,
    YARD,
    YEAR
}
